language: python
python:
    - "3.4"
    - "3.5"
addons:
      postgresql: '9.3'
install:
    - pip install -r requirements/development.txt
script:
    - pep8 .
notifications:
  slack: fcschoolproj1:yxlTHow3cPELACD1AWzqDwxj
